trigger-time=0.
gaussian-noise=True

coherence-test=False
detectors=['H1', 'L1']
duration=4.0
generation-seed=None
sampling-frequency=2048.0

injection=True
injection-file=/home/samanwaya.mukherjee/bilby-tidalheating/bilby/bilby-pipe-test/injection_file_5_samples.json
injection-numbers=None
injection-waveform-approximant=IMRPhenomD_Horizon
injection-frequency-domain-source-model=bilby.gw.source_tidalheating.binary_compact_object_lal_pp_base
injection-waveform-arguments={minimum_frequency: 20.0, maximum_frequency_function: 'f_cut_IMRPhenomD', TH_in_inspiral: True}

################################################################################
## Job submission arguments
################################################################################

accounting=ligo.dev.o5.cbc.pe.bilby
accounting-user=samanwaya.mukherjee
label=bilby-pipe-tidal-test
outdir=/home/samanwaya.mukherjee/bilby-tidalheating/bilby/bilby-pipe-test/outdir-bilby-test
request-disk=2
request-cpus=8
conda-env=/home/samanwaya.mukherjee/.conda/envs/bilby-tidalheating
submit=False
getenv = [PATH, PYTHONPATH, PKG_CONFIG_PATH, LAL_DATADIR]
################################################################################
## Likelihood arguments
################################################################################

calibration-marginalization=False
distance-marginalization=False
distance-marginalization-lookup-table=None
phase-marginalization=False
time-marginalization=False
jitter-time=True
reference-frame=sky
time-reference=geocent
likelihood-type=GravitationalWaveTransient
calibration-lookup-table=None
roq-folder=None
roq-linear-matrix=None
roq-quadratic-matrix=None
roq-weights=None
roq-weight-format=hdf5
roq-scale-factor=1
fiducial-parameters=None
update-fiducial-parameters=False
epsilon=0.025
extra-likelihood-kwargs=None

################################################################################
## Output arguments
################################################################################

plot-trace=True
plot-data=True
plot-injection=False
plot-spectrogram=False
plot-calibration=False
plot-corner=True
plot-marginal=False
plot-skymap=False
plot-waveform=False
plot-format=png
create-summary=True
email=None
notification=Never
existing-dir=None
webdir=/home/samanwaya.mukherjee/public_html/bilby-tidal-test/
result-format=hdf5

################################################################################
## Prior arguments
################################################################################

default-prior=BCOPriorDict
deltaT=0.2
prior-file=/home/samanwaya.mukherjee/bilby-tidalheating/bilby/bilby/gw/prior_files/aligned_spins_bco.prior
enforce-signal-duration=False

################################################################################
## Sampler arguments
################################################################################

sampler=dynesty
sampling-seed=None
n-parallel=1
sampler-kwargs={'nlive': 100, 'naccept': 60, 'check_point_plot': True, 'check_point_delta_t': 1800, 'print_method': 'interval-60', 'sample': 'acceptance-walk', 'npool': 4}
reweighting-configuration=None
reweight-nested-samples=True

################################################################################
## Waveform arguments
################################################################################

waveform-generator=bilby.gw.waveform_generator.WaveformGenerator
catch-waveform-errors=True
waveform-approximant=IMRPhenomD_Horizon
frequency-domain-source-model=bilby.gw.source_tidalheating.binary_compact_object_lal_pp_base
conversion-function=bilby.gw.conversion.convert_to_binary_compact_object_parameters
waveform-arguments-dict={minimum_frequency: 20.0, maximum_frequency_function: 'f_cut_IMRPhenomD', TH_in_inspiral: True}
